### ISSUE TITLE
Hall of fame

### ISSUE THREAD

**Issue by rishabhKalakoti** [Codeshows/codeshows.github.io#21]
Have something like a hall of fame that displays the winners of contest together.
Idea 1:
1st rank Gold medal, 2nd Silver, 3rd Bronze.
Display all winners together showing the different medals they got
Idea 2:
Display the winners of only the latest contest. And till the next contest, those people will be displayed on the website.
The different ideas are welcome and can be discusses in this issue itself.
Idea 3:
We can just have a list of top scorers without the ranks.

**Comment by Sumo99** [comment]
Where can one find the top scores, If i go here for the leader board of any contest, it never loads.

example: https://www.hackerearth.com/challenges/college/CodeFriday-CodeShows-Contest-3/leaderboard/

**Comment by rishabhKalakoti** [comment]
The leaderboard seems locked. You willl have to get that personally. DM me on whatsApp or something, I will get you the results or the top three or whatever you try implementing. Also mention what do you exactly try to implement. I think it will be fine to display top scorers of just the latest contest instead of all the contest ranks.

**Comment by amoranu** [comment]
Idea-2 seems good.
A page based on Idea-1 will get crowded over time, so we can show winners of latest contest as current champions.

**Comment by Surya1231** [comment]
Yes idea-2 can be implemented easily

**Comment by rishabhKalakoti** [comment]
I think hall of fame should be on the home page with a notification section that displays the recent or upcoming events. About can be moved to a different section.
