### ISSUE TITLE
Contacts to footer

### ISSUE THREAD

**Issue by rishabhKalakoti** [Codeshows/codeshows.github.io#7]
Move **Contact Us** to a footer (preferably) or to the sidebar.

**Comment by Surya1231** [comment]
Means Telegram And Facebook Link directly in sidebar??

**Comment by rishabhKalakoti** [comment]
Yes. Its un-utilized space. And its better to have contacts on every page.

**Comment by Surya1231** [comment]
ok boss i was also thinking the same

**Comment by Surya1231** [comment]
Added to Side bar

**Comment by Surya1231** [comment]
Will try to merge it in Footer Once a nice footer is designed
